// Generated by .NET Reflector from E:\svn\Tags\TouchPro\Unity_TouchPro\Assets\Opencoding\DLLs\Opencoding.Shared.dll
namespace Assets.Scripts.Utilities
{
    using System;
    using System.Runtime.CompilerServices;

    public static  class ArrayUtils
    {
        public static void Populate<T>(this T[] data, T value)
        {
            for (int i = 0; i < data.Length; i++)
            {
                data[i] = value;
            }
        }

        public static T[] SubArray<T>(this T[] data, int index, int length)
        {
            T[] destinationArray = new T[length];
            Array.Copy(data, index, destinationArray, 0, length);
            return destinationArray;
        }

      

    }
}
