// Generated by .NET Reflector from C:\ProgramData\Red Gate\.NET Reflector\DevPath\Opencoding.Console.dll
namespace Assets.Scripts.ConsoleController.Console
{
    using UnityEngine;

    public class ImageFilesContainer : ScriptableObject
    {
        public Texture2D _ActiveGradient;
        public Texture2D _AssertIcon;
        public Texture2D _BackgroundGradient;
        public Texture2D _CheckboxChecked;
        public Texture2D _CheckboxUnchecked;
        public Texture2D _ClearIcon;
        public Texture2D _CloseButton;
        public Texture2D _CloseKeyboardIcon;
        public Texture2D _ConsoleInputIcon;
        public Texture2D _ErrorIcon;
        public Texture2D _ExceptionIcon;
        public Texture2D _FilterActiveIcon;
        public Texture2D _HelpIcon;
        public Texture2D _HighlightGradient;
        public Texture2D _InfoIcon;
        public Texture2D _MaximizeIcon;
        public Texture2D _MinimizeTopIcon;
        public Texture2D _NextHistoryItemIcon;
        public Texture2D _PreviousHistoryItemIcon;
        public Texture2D _RedBackgroundGradient;
        public Texture2D _RunIcon;
        public Texture2D _ScrollbarThumb;
        public Texture2D _SearchIcon;
        public Texture2D _SettingsIcon;
        public Texture2D _SettingsPopupBackground;
        public Texture2D _SuggestionButtonBackground;
        public Texture2D _WarningIcon;
        public Texture2D _clean;
    }
}
