// Generated by .NET Reflector from C:\ProgramData\Red Gate\.NET Reflector\DevPath\Opencoding.Console.dll
namespace Assets.Scripts.ConsoleController.Console
{
    using UnityEngine;

    public class Settings : ScriptableObject
    {
        //[HideInInspector]
        public string OpenAndCloseKeys = "~";
        //[HideInInspector]
        public bool PauseGameWhenOpen;
        //[HideInInspector]
        public float fWindowPercent = 1.0f;//控制台窗口比例
        public bool bDontDestroy = false;

        public enum SelectedTouchDetector
        {
            //NONE,
            TWO_FINGER_SWIPE_DOWN = 1,
            //THREE_FINGERS_HELD
        }

        public SelectedTouchDetector _eSelectTouchDetector;
    }
}
